package com.auditcom.persistqueue.domain;

import java.time.LocalDateTime;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * This class was automatically generated by the data modeler tool.
 */

@Getter
@Setter
@Entity
@Table(name = "resultado_alimento_acordante_entrada")
@ToString
public class ResultadoAlimentoAcordanteEntrada implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;
	@Column(name = "valor_imposto")
	private double valorImposto;
	@Column(name = "valor_base_de_calculo")
	private double valorBaseDeCalculo;
	@Column(name = "percentual_carga_liquida")
	private Double percentualCargaLiquida;
	@Column(name = "calcular_imposto")
	private boolean calcularImposto;
	@Column(name = "simples_nacional")
	private boolean simplesNacional;
	private String mensagem;
	@Column(name = "regiao_emitente")
	private String regiaoEmitente;
	@Column(name = "regiao_destinatario")
	private String regiaoDestinatario;
	private String fluxo;
	@Column(name = "tipo_produto")
	private String tipoProduto;
	private String categoria;
	@Column(name = "data_criacao")
	private LocalDateTime dataCriacao;

}
