package com.auditcom.persistqueue.domain;

import java.time.LocalDateTime;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * This class was automatically generated by the data modeler tool.
 */

@Entity
@Table(name = "resultado_alimento_acordante_entrada")
public class ResultadoAlimentoAcordanteEntrada implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;
	@Column(name = "valor_imposto")
	private double valorImposto;
	@Column(name = "valor_base_de_calculo")
	private double valorBaseDeCalculo;
	@Column(name = "percentual_carga_liquida")
	private Double percentualCargaLiquida;
	@Column(name = "calcular_imposto")
	private boolean calcularImposto;
	@Column(name = "simples_nacional")
	private boolean simplesNacional;
	private String mensagem;
	@Column(name = "regiao_emitente")
	private String regiaoEmitente;
	@Column(name = "regiao_destinatario")
	private String regiaoDestinatario;
	private String fluxo;
	@Column(name = "tipo_produto")
	private String tipoProduto;
	private String categoria;
	@Column(name = "data_criacao")
	private LocalDateTime dataCriacao;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public double getValorImposto() {
		return valorImposto;
	}

	public void setValorImposto(double valorImposto) {
		this.valorImposto = valorImposto;
	}

	public double getValorBaseDeCalculo() {
		return valorBaseDeCalculo;
	}

	public void setValorBaseDeCalculo(double valorBaseDeCalculo) {
		this.valorBaseDeCalculo = valorBaseDeCalculo;
	}

	public Double getPercentualCargaLiquida() {
		return percentualCargaLiquida;
	}

	public void setPercentualCargaLiquida(Double percentualCargaLiquida) {
		this.percentualCargaLiquida = percentualCargaLiquida;
	}

	public boolean isCalcularImposto() {
		return calcularImposto;
	}

	public void setCalcularImposto(boolean calcularImposto) {
		this.calcularImposto = calcularImposto;
	}

	public boolean isSimplesNacional() {
		return simplesNacional;
	}

	public void setSimplesNacional(boolean simplesNacional) {
		this.simplesNacional = simplesNacional;
	}

	public String getMensagem() {
		return mensagem;
	}

	public void setMensagem(String mensagem) {
		this.mensagem = mensagem;
	}

	public String getRegiaoEmitente() {
		return regiaoEmitente;
	}

	public void setRegiaoEmitente(String regiaoEmitente) {
		this.regiaoEmitente = regiaoEmitente;
	}

	public String getRegiaoDestinatario() {
		return regiaoDestinatario;
	}

	public void setRegiaoDestinatario(String regiaoDestinatario) {
		this.regiaoDestinatario = regiaoDestinatario;
	}

	public String getFluxo() {
		return fluxo;
	}

	public void setFluxo(String fluxo) {
		this.fluxo = fluxo;
	}

	public String getTipoProduto() {
		return tipoProduto;
	}

	public void setTipoProduto(String tipoProduto) {
		this.tipoProduto = tipoProduto;
	}

	public String getCategoria() {
		return categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

	public LocalDateTime getDataCriacao() {
		return dataCriacao;
	}

	public void setDataCriacao(LocalDateTime dataCriacao) {
		this.dataCriacao = dataCriacao;
	}

}
